[package]
name = "hypervisor_test"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
x86 = "0.52.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
